import { Inter } from "next/font/google";
import "@/app/globals.css";
import style from "@/app/globals.module.css";
import Header from "@/components/ui/Header/Header";
import Main from "@/components/ui/Main/Main";
import Footer from "@/components/ui/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body className={style.body}>
        <Header />
        <main className={style.main}>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
